server:
  port: 3979

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: LBnrKcXH4pe1xhsCDCbaqbsLFD01Z/yEqnM8llt4HDP2dnE3q+Hh+w77q40uauDNtI6XcaG4rHJkcGcTU1FHdR05W0b2DH6dYQ3KmmgQWJ8=